version: '3.9'

# docker exec -it postgres_container bash
# psql -U postgres -d dream_shops_db

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5433:5432"
    restart: unless-stopped